exception_details/__init__.py,sha256=iP0FZhpcSpDZH6MFD8K7_1vH4FFUFZV0RRJ3ZAIKKdM,132
exception_details/exception_details.py,sha256=-KiuxCqkGYbjjlSg6CKOcNVme-JWMQTyRVDZE5VRPms,4411
exception_details-0.0.1.dist-info/LICENSE.txt,sha256=9HsmUbkMFZDTY_7eyGX6_7F-jwhNF1PxA_6J37d5YPA,1095
exception_details-0.0.1.dist-info/METADATA,sha256=CRDsTM1S4pSowBbYyZido3mGDKmS1GYGP87yJ54wpQ4,700
exception_details-0.0.1.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
exception_details-0.0.1.dist-info/top_level.txt,sha256=oI-s3hCBa08Bax10Tt2Du6FiUdeo6FzFjHYv6bjEEpk,18
exception_details-0.0.1.dist-info/RECORD,,
